scrape_configs:

  - job_name: 'dockerswarm-cadvisor'

    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes

    relabel_configs:
      # ================================================================================
      # Override prometheus internal labels
      # ================================================================================
      - source_labels:
        - __meta_dockerswarm_node_id
        target_label: __address__
        replacement: cadvisor.$1.cluster.local:8080

      # Set hostname as instance label
      - source_labels:
        - __meta_dockerswarm_node_address
        target_label: instance

      # ================================================================================
      # Label mapping
      # ================================================================================
      - action: labelmap
        regex: __meta_(dockerswarm_node_.+)
      - action: labelmap
        regex: __meta_dockerswarm_(node_(?:id|hostname))

    metric_relabel_configs:
      # Set "container" to the Docker Swarm's Task Name of the target container
      - source_labels:
        - name
        target_label: container

      # ================================================================================
      # Label mapping
      # ================================================================================
      - action: labelmap
        regex: container_label_com_(docker_.*)

      # ================================================================================
      # Kubernetes compatible relabeling
      # - namespace
      # - deployment
      # - pod
      # ================================================================================
      # # Set Kubernetes's Namespace with "com.docker.stack.namespace" label
      - source_labels:
        - container_label_com_docker_stack_namespace
        target_label: namespace

      # Set Kubernetes's Deployment with "com.docker.stack.namespace" label
      - source_labels:
        - container_label_com_docker_stack_namespace
        target_label: deployment

      # Set Kubernetes's Pod Name with Docker Swarm's Service Name
      - source_labels:
        - container_label_com_docker_swarm_service_name
        target_label: pod
